/**
 * @description User
 */
export const CURRENT_USER_FETCH = 'CURRENT_USER_FETCH';
export const CURRENT_USER_FETCH_FAILED = 'CURRENT_USER_FETCH_FAILED';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REQ_CODE_SUCCESS = 'REQ_CODE_SUCCESS';
export const DETAIL_RESET_SUCCESS = 'DETAIL_RESET_SUCCESS';
export const GET_USERS_BY_NAME = 'GET_USERS_BY_NAME';
export const GET_USERS_BY_NAME_SUCCESS = 'GET_USERS_BY_NAME_SUCCESS';
export const GET_USERS_BY_ID_SUCCESS = 'GET_USERS_BY_ID_SUCCESS';
export const CLEAR_FRIENDSLIST = 'CLEAR_FRIENDSLIST';
export const GET_MYFRIENDS_LIST_SUCCESS = 'GET_MYFRIENDS_LIST_SUCCESS';
export const UPDATE_SUCCESSFUL = 'UPDATE_SUCCESSFUL';
export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCCESS';
export const REMOVE_FRIEND_FAILED = 'REMOVE_FRIEND_FAILED';
export const REMOVE_FRIEND_FETCHING = 'REMOVE_FRIEND_FETCHING';
export const GET_TEACHERS_BY_NAME = 'GET_TEACHERS_BY_NAME';
export const GET_TEACHERS_BY_NAME_SUCCESS = 'GET_TEACHERS_BY_NAME_SUCCESS';
export const CURRENT_TEACHER_FETCH = 'CURRENT_TEACHER_FETCH';
export const CURRENT_TEACHER_FETCH_FAILED = 'CURRENT_TEACHER_FETCH_FAILED';
export const CLEAR_TEACHERSLIST = 'CLEAR_TEACHERSLIST';
export const GET_MYTEACHERS_LIST_SUCCESS = 'GET_MYTEACHERS_LIST_SUCCESS';
export const REMOVE_TEACHER_SUCCESS = 'REMOVE_TEACHER_SUCCESS';
export const REMOVE_TEACHER_FAILED = 'REMOVE_TEACHER_FAILED';
export const REMOVE_TEACHER_FETCHING = 'REMOVE_TEACHER_FETCHING';
export const GET_STUDENT_INFO = 'GET_STUDENT_INFO';
export const GET_STUDENT_INFO_SUCCESS = 'GET_STUDENT_INFO_SUCCESS';
export const GET_STUDENT_INFO_FAILED = 'GET_STUDENT_INFO_FAILED';
/**
 * @description Quiz
 */
export const QUIZES_FETCHING = 'QUIZES_FETCHING';
export const QUIZES_FETCH_SUCCESS = 'QUIZES_FETCH_SUCCESS';
export const QUIZES_SUMMERY_FETCH_SUCCESS = 'QUIZES_SUMMERY_FETCH_SUCCESS';
export const QUIZES_TOP_SUCCESS = 'QUIZES_TOP_SUCCESS';
export const QUIZES_MYSCORE_SUCCESS = 'QUIZES_MYSCORE_SUCCESS';
export const QUIZES_FETCH_FAILED = 'QUIZES_FETCH_FAILED';
export const SET_QUIZ_TYPE = 'SET_QUIZ_TYPE';
export const SET_QUIZ_COLLECTION = 'SET_QUIZ_COLLECTION';
export const SET_QUIZ_LEVEL = 'SET_QUIZ_LEVEL';

/**
 * @description Battle
 */
export const BATTLE_FETCHING = 'BATTLE_FETCHING';
export const POST_BATTLE = 'POST_BATTLE';
export const POST_BATTLE_SUCCESS = 'POST_BATTLE_SUCCESS';
export const POST_BATTLE_FAILD = 'POST_BATTLE_FAILD';
export const BATLLE_START = 'BATLLE_START';
export const JOIN_BATLLE_START = 'JOIN_BATLLE_START';
export const INVING_FRIEND = 'INVING_FRIEND';
export const INVING_FRIEND_FAILED = 'INVING_FRIEND_FAILED';
export const INVING_FRIEND_SUCCESS = 'INVING_FRIEND_SUCCESS';
export const BATTLE_QNS_FECHING = 'BATTLE_QNS_FECHING';
export const BATTLE_QNS_SUCCESS = 'BATTLE_QNS_SUCCESS';
export const BATTLE_QNS_FAILED = 'BATTLE_QNS_FAILED';
export const FRIENDS_REQUEST_FECHING = 'FRIENDS_REQUEST_FECHING';
export const FRIENDS_REQUEST_SUCCESS = 'FRIENDS_REQUEST_SUCCESS';
export const FRIENDS_REQUEST_FAILED = 'FRIENDS_REQUEST_FAILED';
export const UPDATE_BATTLE_RESULT_FECHING = 'UPDATE_BATTLE_RESULT_FECHING';
export const UPDATE_BATTLE_RESULT_SUCCESS = 'UPDATE_BATTLE_RESULT_SUCCESS';
export const UPDATE_BATTLE_RESULT_FAILED = 'UPDATE_BATTLE_RESULT_FAILED';
export const ADD_FRIEND_REQUEST_FECHING = 'ADD_FRIEND_REQUEST_FECHING';
export const ADD_FRIEND_REQUEST_SUCCESS = 'ADD_FRIEND_REQUEST_SUCCESS';
export const ADD_FRIEND_REQUEST_FAILED = 'ADD_FRIEND_REQUEST_FAILED';
export const CLEAR_FRIEND_REQUEST_LIST = 'CLEAR_FRIEND_REQUEST_LIST';
export const UPDATE_FRIEND_REQUEST_FETCHING = 'UPDATE_FRIEND_REQUEST_FETCHING';
export const UPDATE_FRIEND_REQUEST_SUCCESS = 'UPDATE_FRIEND_REQUEST_SUCCESS';
export const UPDATE_FRIEND_REQUEST_FAILED = 'UPDATE_FRIEND_REQUEST_FAILED';
export const BATTLE_END_QNS_SUCCESS = 'BATTLE_END_QNS_SUCCESS';
export const BATTLE_END_QNS_FAILED = 'BATTLE_END_QNS_FAILED';
export const SAVE_BATTLE_SUCCESS = 'SAVE_BATTLE_SUCCESS';
export const BATTLE_SUMMARY_SUCCESS = 'BATTLE_SUMMARY_SUCCESS';
export const BATTLE_SUMMARY_FAILED = 'BATTLE_SUMMARY_FAILED';
export const BATTLE_OPEN_QNS_SUCCESS = 'BATTLE_OPEN_QNS_SUCCESS';
export const BATTLE_OPEN_QNS_FAILED = 'BATTLE_OPEN_QNS_FAILED';
export const BATTLE_POSITION_SUCCESS = 'BATTLE_POSITION_SUCCESS';
export const BATTLE_POSITION_FAILED = 'BATTLE_POSITION_FAILED';
export const BATTLE_POSITION_FETCHING = 'BATTLE_POSITION_FETCHING';
export const BATTLE_POSITION_UPDATE = 'BATTLE_POSITION_UPDATE';
export const PREPARE_OPEN_BATTLE_SUCCESS = 'PREPARE_OPEN_BATTLE_SUCCESS';
export const PREPARE_OPEN_BATTLE_FAILED = 'PREPARE_OPEN_BATTLE_FAILED';
export const ADD_TEACHER_REQUEST_FECHING = 'ADD_TEACHER_REQUEST_FECHING';
export const ADD_TEACHER_REQUEST_SUCCESS = 'ADD_TEACHER_REQUEST_SUCCESS';
export const ADD_TEACHER_REQUEST_FAILED = 'ADD_TEACHER_REQUEST_FAILED';
export const CLEAR_TEACHER_REQUEST_LIST = 'CLEAR_TEACHER_REQUEST_LIST';
export const UPDATE_TEACHER_REQUEST_FETCHING =
  'UPDATE_TEACHER_REQUEST_FETCHING';
export const UPDATE_TEACHER_REQUEST_SUCCESS = 'UPDATE_TEACHER_REQUEST_SUCCESS';
export const UPDATE_TEACHER_REQUEST_FAILED = 'UPDATE_TEACHER_REQUEST_FAILED';
export const TEACHERS_REQUEST_FECHING = 'TEACHERS_REQUEST_FECHING';
export const TEACHERS_REQUEST_SUCCESS = 'TEACHERS_REQUEST_SUCCESS';
export const TEACHERS_REQUEST_FAILED = 'TEACHERS_REQUEST_FAILED';
export const INVING_TEACHER = 'INVING_TEACHER';
export const INVING_TEACHER_FAILED = 'INVING_TEACHER_FAILED';
export const INVING_TEACHER_SUCCESS = 'INVING_TEACHER_SUCCESS';
